name: 'Pull request comments from clang-tidy reports'
description: 'Post clang-tidy warnings as review comments on pull requests'
inputs:
  github_token:
    description: 'The GitHub token'
    required: true
  clang_tidy_fixes:
    description: 'Path to the clang-tidy fixes YAML file'
    required: true
  pull_request_id:
    description: 'Pull request id (otherwise attempt to extract it from the GitHub metadata)'
    required: false
    default: ''
  request_changes:
    description: 'Request changes if there are clang-tidy issues (otherwise leave a comment)'
    required: false
    default: 'false'
  suggestions_per_comment:
    description: 'The number of suggestions per comment (smaller numbers work better for heavy pull requests)'
    required: false
    default: '10'
  repo_path_prefix:
    description: 'The path to repo when code is analyzed with clang-tidy; may set to "/__w" for users who run clang-tidy in a docker container'
    required: false
    default: '/home/runner/work'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cpu'
  color: 'green'
