name: 'Pull request comments from clang-tidy reports'
description: 'Post clang-tidy warnings as review comments on pull requests'
inputs:
  github_token:
    description: 'The GitHub token'
    required: true
  clang_tidy_fixes:
    description: 'Path to the clang-tidy fixes YAML file'
    required: true
  pull_request_id:
    description: 'Pull request id (otherwise attempt to extract it from the GitHub metadata)'
    required: false
    default: ''
  request_changes:
    description: 'Request changes if there are clang-tidy issues (otherwise leave a comment)'
    required: false
    default: 'false'
  suggestions_per_comment:
    description: 'The number of suggestions per comment (smaller numbers work better for heavy pull requests)'
    required: false
    default: '10'
  repo_path_prefix:
    description: 'The path to repo when code is analyzed with clang-tidy; may set to "/__w" for users who run clang-tidy in a docker container'
    required: false
    default: '/home/runner/work'


runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: "3.11"
        update-environment: false
    - name: Setup venv
      run: ${{ steps.setup-python.outputs.python-path }} -m venv ${GITHUB_ACTION_PATH}/venv

      shell: bash -l {0}
    - name: Install dependencies
      run: ${GITHUB_ACTION_PATH}/venv/bin/python -m pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash -l {0}
    - name: Run action
      run: ${GITHUB_ACTION_PATH}/action_launcher.bash
      shell: bash -l {0}
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_CLANG_TIDY_FIXES: ${{ inputs.clang_tidy_fixes }}
        INPUT_PULL_REQUEST_ID: ${{ inputs.pull_request_id }}
        INPUT_REQUEST_CHANGES: ${{ inputs.request_changes }}
        INPUT_SUGGESTIONS_PER_COMMENT: ${{ inputs.suggestions_per_comment }}
        INPUT_REPO_PATH_PREFIX: ${{ inputs.repo_path_prefix }}
branding:
  icon: 'cpu'
  color: 'green'
